### PR TITLE
REFACTOR simplify getRelatedVideos()

### LINKED ISSUE #8: REFACTOR simplify related video query
https://github.com/dynamic/silverstripe-html5video/blob/master/code/Video.php#L112-L119

The code above can probably be paired to speed up the code:

``` php
    /**
     * @return DataList|bool
     */
    public function getRelatedVideos()
    {
        if ($this->Parent() && $this->Parent()->ClassName == 'VideoGroup') {
            return $this->Parent()->getVideoList()->exclude('ID', $this->ID);
        }

        return false;
    }
```

### PR DESCRIPTION
**Pull request by muskie9**
closes #8

### CODE REVIEW

**Comment by muskie9** [comment]
@jsirish I noticed the docblocks for the method states `DataList` as a returned type, should that be `PaginatedList` instead as the `Parent()->getVideoList()` returns type `PaginatedList`?

**Comment by jsirish** [comment]
looks good, nice simplification

**Comment by jsirish** [comment]
yeah that should be PaginatedList

**Comment by muskie9** [comment]
My other PR changes the type to DataList, so we should be good once that's finalized and merged.

**Pull request merged**
